version: '2'
services:
  mosquitto:
    image: ansi/mosquitto
    ports:
      - "1883:1883"

    command: /usr/local/sbin/mosquitto -v -c /etc/mosquitto/mosquitto.conf

    volumes:
      - $PWD/mosquitto.conf:/etc/mosquitto/mosquitto.conf
      - $PWD/data:/home/mosquitto/data

  influxdb:
    image: influxdb
    ports:
      - "8083:8083"
      - "8086:8086"

    volumes:
      - $PWD/data:/var/lib/influxdb/data
      - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf

    depends_on:
      - chronograf
      - kapacitor

  telegraf:
    image: telegraf
    ports:
      - "8125:8125"
      - "8092:8092"
      - "8094:8094"

    depends_on:
      - influxdb
      - mosquitto

  chronograf:
    image: chronograf
    ports:
      - "10000:10000"

  kapacitor:
    image: kapacitor
    ports:
      - "9092:9092"

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

